server:
  port: 8093
spring:
  # Banner
  main:
    banner-mode: console
  output:
    ansi:
      enabled: always
  banner:
    location: banner/catalog-banner.txt
  # Application Name
  application:
    name: catalog-service
  #Security
  security:
    user:
      name: user
      password: default
  ## Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db_catalog
    username: sa
    password: password
  ## JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # dev only set to true for debugging purposes
    show-sql: true
    ## JPA - HIBERNATE
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  # H2 Database
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
        web-admin-password: 1234
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/dashboard



