server:
  port: 8888
spring:
  application:
    name: config-server
#TODO configuration location ect...
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/NMandisa/config-repo