server:
  port: 8065
    #servlet:
    #context-path: api.localhost/
    #application-display-name: product-search-service
    #error:
    #include-binding-errors: always
    #include-message: always
    #include-stacktrace: never
  #include-exception: true
spring:
  application:
    name: product-search-service
  # Banner
  main:
    banner-mode: console
  output:
    ansi:
      enabled: always
  banner:
    location: banner/product-search-banner.txt
  #Security
  security:
    user:
      name: user
      password: default
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/dashboard

