spring:
  application:
    name: store-locator-service
  #elasticsearch:
   # uris: localhost:9200
    #path-prefix: /
    #password: 1234

eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/dashboard